### ISSUE TITLE
"Whispered something but you can't hear what."

### ISSUE THREAD

**Issue by MCVDK** [ThroneCraft/issues#53] opened 2020-10-25 17:43 UTC
**Describe the bug**
When executing the whisper command- it always shows you the 'whispered something but you can't hear what' message together with the actual message of the player.

**Screenshots**
[Screenshot](https://i.gyazo.com/7e8e380b5557af9390f0f602a43b29e7.png)
[Screenshot](https://i.gyazo.com/f107725ab2966446f82879db7dfd6f9a.png)

**Additional context**
I do not believe more is required.

***Minecraft username:***
MCVDK

**Comment by jvdoorn** [comment] 2020-10-25 18:27
Duplicate of #48.

**Closed** 2020-10-25 18:28 UTC
Labels: bug
