### ISSUE TITLE
Syntactical Error in Rolling Commands

### ISSUE THREAD

**Issue by chernayas** [ThroneCraft/issues#50] opened 2020-10-22 18:19 UTC
**Describe the bug**

When rolling in combat, a syntactical typo occurs where the thing being rolled and the word 'and' do not have a space between them.

**Screenshots**

https://gyazo.com/3eb0bac2d792214a5c11f0c3d449d82d

**Additional context**

N/A

***Minecraft username:***

Chernaya

**Comment by jvdoorn** [comment] 2020-10-22 18:20
Duplicate of #49.

**Closed by jvdoorn** 2020-10-22 18:20 UTC
Labels: bug
