### ISSUE TITLE
Outpost tags

### ISSUE THREAD

**Issue by BackupPT** [ThroneCraft/issues#139] opened 2021-01-18 21:28 UTC
**Describe the bug**

Outpost tags are broken in game right now as all outposts have white tags.

**Screenshots**

https://prnt.sc/x5p7ca
https://prnt.sc/x5p8if

***Minecraft username:***

Backup__

**Comment by Brsssh** [comment] 2021-01-19 00:16
Duplicate of Issue #135

**Closed as completed by Brsssh** 2021-01-19 00:16 UTC
Labels: bug
